// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuLAsP2cfekCEKK-Fqegapgd-sk9D9BE8',
    appId: '1:993446893167:web:2f1302d6a3802dadfd9f9a',
    messagingSenderId: '993446893167',
    projectId: 'fir-1ba20',
    authDomain: 'fir-1ba20.firebaseapp.com',
    storageBucket: 'fir-1ba20.appspot.com',
    measurementId: 'G-M9J60EVG96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABCzNAXAJvExuw7Kb8oJ--4YDjteHUl4w',
    appId: '1:993446893167:android:43556f1f4a99d168fd9f9a',
    messagingSenderId: '993446893167',
    projectId: 'fir-1ba20',
    storageBucket: 'fir-1ba20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2I7ZE7GaYGGqK-6qkpVHvhiJQ6Xv12Qc',
    appId: '1:993446893167:ios:c6444dec691de3fdfd9f9a',
    messagingSenderId: '993446893167',
    projectId: 'fir-1ba20',
    storageBucket: 'fir-1ba20.appspot.com',
    iosBundleId: 'com.example.blogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2I7ZE7GaYGGqK-6qkpVHvhiJQ6Xv12Qc',
    appId: '1:993446893167:ios:ab570cfa3de32172fd9f9a',
    messagingSenderId: '993446893167',
    projectId: 'fir-1ba20',
    storageBucket: 'fir-1ba20.appspot.com',
    iosBundleId: 'com.example.blogger.RunnerTests',
  );
}
